### ISSUE TITLE
EISDIR: illegal operation on a directory, read on @eadir folders, synology NAS

### ISSUE THREAD

**Issue by nicoduj** [simonlast/node-persist#124]
Hi, 

don't know if it can be fixed or if it is even possible, but I had a long time trying to solve / understand the following error.

The problem was on a docker image that runs some homebridge configuration on a synology NAS, with some mounted directory between container and the host (on the synology). synology create those hidden directories (@eadir) when it indexes the folder for media content (which can be prevented), but also sometimes when you access theme from a mac to store metadata. The problem is that they are invisible, but the lib crashes when it encountere them (since they do not have the right permission). Maybe it could be handled in some way to avoid a whole system crash that is really tricky to understand !

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:524:3)
    at tryReadSync (fs.js:349:20)
    at Object.readFileSync (fs.js:386:19)
    at LocalStorage.parseFileSync (/homebridge/node_modules/homebridge-dummy/node_modules/node-persist/src/local-storage.js:661:35)
    at LocalStorage.parseStorageDirSync (/homebridge/node_modules/homebridge-dummy/node_modules/node-persist/src/local-storage.js:615:26)
    at LocalStorage.initSync (/homebridge/node_modules/homebridge-dummy/node_modules/node-persist/src/local-storage.js:142:14)
    at Object.nodePersist.initSync (/homebridge/node_modules/homebridge-dummy/node_modules/node-persist/src/node-persist.js:37:32)
    at new DummySwitch (/homebridge/node_modules/homebridge-dummy/index.js:23:16)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:355:50
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:328:29)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:154:12)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:78:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

**Comment by akhoury** [comment]
are you still having this issue? I think we faced a similar issue with Google Drive it was fixed in a more recent version that you're using.

**Comment by akhoury** [comment]
actually you can use `forgiveParseErrors: true` in the init options to ignore unrecognized files and directories in your storage dir

>>> in some cases, you (or some other service) might add non-valid storage files to your storage dir, i.e. Google Drive, make this true if you'd like to ignore these files and not throw an error
