### ISSUE TITLE
Issue with empty directory, node-persist crashing

### ISSUE THREAD

**Issue by bluepuma77** [simonlast/node-persist#30]
I installed node-persist via npm and it continuously crashed on me (node.js 0.10 and 0.12 on Debian).
```
app.js- path.js:471
app.js-       throw new TypeError('Arguments to path.join must be strings');
app.js-             ^
app.js- TypeError: Arguments to path.join must be strings
app.js-     at Object.posix.join (path.js:471:13)
app.js-     at parseDirSync (/node/node_modules/node-persist/node-persist.js:681:49)
app.js-     at parseDataDirSync (/node/node_modules/node-persist/node-persist.js:617:12)
app.js-     at Object.exports.initSync (/node/node_modules/node-persist/node-persist.js:114:5)
```
I found a potential issue in line 678 in file node-persist/node-persist.js
```
        var arr = fs.readdirSync(dir);
        for (var i in arr) {
            var curr = arr[i];
```
If arr is empty, then "i" becomes "clean" (if you print it) and curr goes crazy and later path.join crashes.

I fixed it with:
```
        for (var i=0; i<arr.length; i++) {
```

**Comment by simonlast** [comment]
Looks great, could you file a PR?

**Comment by ir0ny1** [comment]
Closed - waiting on Npm publish
