### ISSUE TITLE
Illegal operation on a directory error

### ISSUE THREAD

**Issue by bostondevin** [simonlast/node-persist#49]
What's this one about? I haven't specified a dir or anything - just using your sample code:

Error: EISDIR: illegal operation on a directory, open 'persist'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1155:15)
    at Object.LocalStorage.persistKeySync (/websites/demoit/node_modules/node-persist/local-storage.js:457:12)
    at Object.LocalStorage.setItemSync (/websites/demoit/node_modules/node-persist/local-storage.js:275:14)
    at Object.nodePersist.setItemSync (/websites/demoit/node_modules/node-persist/node-persist.js:99:29)
    at Promise.<anonymous> (/websites/demoit/server.js:269:9)
    at Promise.<anonymous> (/websites/demoit/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at emitOne (events.js:77:13)
    at Promise.emit (events.js:169:7)
    at Promise.emit (/websites/demoit/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/websites/demoit/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at Promise.resolve (/websites/demoit/node_modules/mongoose/lib/promise.js:114:23)
    at Promise.<anonymous> (/websites/demoit/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at emitOne (events.js:77:13)
    at Promise.emit (events.js:169:7)

**Comment by akhoury** [comment]
looks like a permission issue. Does the test pass for you?

```bash
cd node_modules/node-persist

# just in case devDependencies weren't installed
npm install 

npm test
```
