### ISSUE TITLE
Accessories must be created with Non-empty display name

### ISSUE THREAD

**Issue by meluvalli** [simonlast/node-persist#82]
I am not 100% sure if this is a node-persist issue or a homebridge issue...  But, only happens when I update node-persist, so thought I would log the issue here in case... 

When I update to the latest node-persist I receive the below error:

C:\HomeBridge\node_modules\npm\lib\platformAccessory.js:16
if (!UUID) throw new Error("Accessories must be created with a valid UUID.");
^

Error: Accessories must be created with a valid UUID.
at new PlatformAccessory (C:\HomeBridge\node_modules\npm\lib\platformAccessory.js:16:20)
at Server._loadCachedPlatformAccessories (C:\HomeBridge\node_modules\npm\lib\server.js:225:31)
at new Server (C:\HomeBridge\node_modules\npm\lib\server.js:53:42)
at module.exports (C:\HomeBridge\node_modules\npm\lib\cli.js:26:16)
at Object. (C:\HomeBridge\node_modules\npm\bin\homebridge:17:22)
at Module._compile (module.js:571:32)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
at Function.Module._load (module.js:439:3)

**Comment by akhoury** [comment]
i dont see how `node-persist` is involved in this stack trace, unless there is a point you're pulling data from node-persist and you lost the `uuid` 

which version of node-persist were you on? if you were on a `1.x.x` you can't easily upgrade to `2.x.x` we've made non-backward changes, https://github.com/simonlast/node-persist#200-change-logs

**Comment by meluvalli** [comment]
Looks like you may be correct.  I was using the version that originally comes with NodeJS which is an older version.  Was trying to update it to the latest and that's when I receive the error.  So, I guess I won't upgrade it :(
